export const ACTION = {
    SIGN_IN: 'SIGN_IN',
    SIGN_UP: 'SIGN_UP',
    SIGN_OUT: 'SIGN_OUT',
    GET_INITIAL_DATA: 'GET_INITIAL_DATA',
    CREATE_WORKSPACE: 'CREATE_WORKSPACE',
    CREATE_CHANNEL: 'CREATE_CHANNEL',
    CREATE_PRIVATEMESSAGE: 'CREATE_PRIVATEMESSAGE',
    CHANGE_CHANNEL: 'CHANGE_CHANNEL',
    CHANGE_WORKSPACE: 'CHANGE_WORKSPACE',
    CHANGE_VIEW: 'CHANGE_VIEW',
    CHANGE_PM_USER: 'CHANGE_PM_USER',
    DELETE_WORKSPACE: 'DELETE_WORKSPACE',
    DELETE_CHANNEL: 'DELETE_CHANNEL',
    RENAME_WORKSPACE: 'RENAME_WORKSPACE',
    CLEAR_VOICE_CONNECTION: 'CLEAR_VOICE_CONNECTION',
    GET_ALL_USERS: 'GET_ALL_USERS',
    UPDATE_ACTIVE_USERS: 'UPDATE_ACTIVE_USERS',
    UPDATE_ACTIVE_STATE: 'UPDATE_ACTIVE_STATE',
    LoadInitialData: 'LoadInitialData',
    ISUSER_AUTHENICATED: 'ISUSER_AUTHENICATED',
    GET_ALL_DATA: 'GET_ALL_DATA',
    ADD_EMOTICON: 'ADD_EMOTICON',

    GET_REMINDERS: 'GET_REMINDERS',
    CREATE_REMINDER: 'CREATE_REMINDER',
    DELETE_REMINDER: 'DELETE_REMINDER',

    GET_PINNED_MESSAGES: 'GET_PINNED_MESSAGES',
    GET_SEARCHED_MESSAGES: 'GET_SEARCHED_MESSAGES',
    REMOVE_PINNED_MESSAGE: 'REMOVE_PINNED_MESSAGE',

    //socket actioons
    SEND_SOCKET_MESSAGE: 'SEND_SOCKET_MESSAGE',
    SEND_SOCKET_PRIVATE_MESSAGE: 'SEND_SOCKET_PRIVATE_MESSAGE',
    RECIEVE_SOCKET_MESSAGE: 'RECIEVE_SOCKET_MESSAGE',
    RECEIVE_SOCKET_PRIVATE_MESSAGE: 'RECEIVE_SOCKET_PRIVATE_MESSAGE',
    ADD_PRIVATE_MESSAGE: 'ADD_PRIVATE_MESSAGE'


}